# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Your awesome title
email: johan.sward86@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://johansward.github.io/Portfolio/" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: jekyll-theme-slate
markdown: kramdown
plugins:
  - jekyll-feed


## Welcome to Johan Swärd's Portfolio

Here you will find selected projects that are a result of my academic research as a Ph.D. and PostDoc in Statistical Signal Process as well as project I have done for my start-ups as well as my private hobby-projects.

![Johan Swärd](/Images/Johan_Sward.jpg)
* TOC
{:toc}


### Selected projects from my Ph.D-studies.
1. [Estimating Periodicities in Symbolic Sequences Using Sparse Modeling.](https://johansward.github.io/Portfolio/Sampling)
2. Off-grid Fundamental Frequency Estimation.
3. Online Estimation of Multiple Harmonic Signals.
4. Designing Optimal Sampling Schemes.

### Selected projects from my Postdoctoral
1. Prostate Localization in MRI.
2. Detecting Alzheimer's in Flow Cytometry.

### Start-up and hobby projects
1. Detecting Voice Anomalies Using Siamese Networks.
2. Removing Snow and Rain from Surveillance Footage.
3. Punctuation-net: Helping me correctly placing commas in Swedish.





# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
